name: wslerry
title: Sains Slides Template
email: 
description: >- # this means to ignore newlines until "baseurl:"
  This is an awesome slide build on reveal.js and jekyll
baseurl: ""
url: ""

encoding: UTF-8

show_dir_listing: false

collections:
  slides:
    output: true
    permalink: /:collection/:name

webrick:
  headers:
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    Referrer-Policy: no-referrer, strict-origin-when-cross-origin
    Strict-Transport-Security: max-age=63072000

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock